name: Build Choreography

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Choreography.sln
    - name: Build
      run: dotnet build ./src/Choreography.sln --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release ./src/Choreography.AspNetCore.UI/Choreography.AspNetCore.UI.csproj --version-suffix "alpha-${GITHUB_RUN_NUMBER}" --output .
    - name: Publish Nuget.org
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
    # - name: Add Github Source
    #   run: dotnet nuget add source --username fals --password ${{secrets.PUBLISH_TO_GITHUB_COM}} --name github https://nuget.pkg.github.com/choreography/index.json
    # - name: Publish Nuget Github
    #   run: dotnet nuget push *.nupkg --source github --skip-duplicate
